# action.yml
name: 'Hugo rsync deployment'
description: 'An action that generates and deploys a static website using Hugo and rsync.'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  doc-dirs:
    description: 'doc directorys'
    required: true
  doc-version:
    description: 'doc version'
    required: false
    default: 'v1'
  doc-domain:
    description: 'doc domain'
    required: true,
    default: ''
  hugo-arguments:
    description: 'Hugo arguments'
    required: false
    default: '--minify'
  rsync-arguments:
    description: 'Rsync arguments'
    required: false
    default: '--archive --compress --xattrs --delete'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.doc-version }}
    - ${{ inputs.doc-dirs }}
    - ${{ inputs.doc-domain }}
    - ${{ inputs.hugo-arguments }}
    - ${{ inputs.rsync-arguments }}
